repo: "responsive-section"
canvasCourse: "web-dev-1"

inherit:
  - naming-restrict-live
  - git-2
  - html
  - google-fonts
  - img-flex
  - css
  - border-box
  - responsive-css
  - responsive-font-sizes
  - body-margin-0
  - screenshots-all

html:
  - path: "index.html"
    outline: false
    has:
      - ['link[href*="Noto+Sans"]', 'The Google Font, `Noto Sans` (regular & bold) is missing']
      - 'section'
      - 'section .wrapper'
      - 'section div'
      - 'section div img'
      - 'section div h2'
      - 'section div p'
      - '.wrapper'
      - '.section-letter'
      - '.section-icon'
      - '.section-body'
    search:
      - 'Dragon'
      - 'Magnanimous, stately, vigorous, strong, proud, noble, direct, dignified, passionate.'

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    has:
      - ['html', 'font', 'normal 100%/1.3 "Noto Sans", sans-serif']
      - ['section', 'background-color', '#e5c30a']
      - ['.wrapper', 'margin', '0 auto']
      - ['.wrapper', 'max-width', '45em']
      - ['section h2']
      - ['section p']
      - ['.section-letter']
      - ['.section-icon']
      - ['@25em', '.section-letter']
    search:
      - 'float\: left'
      - 'float\: right'
      - 'overflow\: hidden'
      - 'width\:'
