repo: "responsive-section"
canvasCourse: "web-dev-1"

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - ['link[href*="Noto+Sans"]', 'The Google Font, `Noto Sans` (regular & bold) is missing']
      - 'section'
      - 'section .wrapper'
      - 'section div'
      - 'section div img'
      - 'section div h2'
      - 'section div p'
      - '.wrapper'
      - '.section-letter'
      - '.section-icon'
      - '.section-body'
      - '.img-flex'
    search:
      - 'Dragon'
      - 'Magnanimous, stately, vigorous, strong, proud, noble, direct, dignified, passionate.'

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['html', 'text-size-adjust', '100%']
      - ['html', '-moz-text-size-adjust', '100%']
      - ['html', '-ms-text-size-adjust', '100%']
      - ['html', '-webkit-text-size-adjust', '100%']
      - ['html', 'font', 'normal 100%/1.3 "Noto Sans", sans-serif']
      - ['*', 'box-sizing', 'inherit']
      - ['body', 'margin', '0']
      - ['.img-flex', 'display', 'block']
      - ['.img-flex', 'width', '100%']
      - ['section', 'background-color', '#e5c30a']
      - ['.wrapper', 'margin', '0 auto']
      - ['.wrapper', 'max-width', '45em']
      - ['section h2']
      - ['section p']
      - ['.section-letter']
      - ['.section-icon']
      - ['@25em', '.section-letter']
      - ['@38em', 'html', 'font-size', '110%']
      - ['@38em', 'html', 'line-height', '1.4']
      - ['@60em', 'html', 'font-size', '120%']
      - ['@60em', 'html', 'line-height', '1.5']
      - ['@90em', 'html', 'font-size', '130%']
    search:
      - '@-moz-viewport'
      - '@-ms-viewport'
      - '@-o-viewport'
      - '@-webkit-viewport'
      - '@viewport'
      - 'float\: left'
      - 'float\: right'
      - 'overflow\: hidden'
      - 'width\:'
    searchNot:
      - ['@media.+\(.*max-width', 'Media queries with `max-width` should not be used — use `min-width` instead']
      - ['@media.+\(.*px', 'Pixel units should not be used in media queries — use `em` instead']
      - ['font-size\s*:\s*.+px', 'Pixel units should not be used for `font-size` — use `rem` instead']
      - ['line-height\s*:\s*.+(px|rem|em)', 'Line heights should not have units']

screenshots:
  - path: "index.html"
    sizes: [320, 400, 650, 980, 1400]
